# Generated by Django 4.2.3 on 2023-08-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0004_jobapplication_current_stage_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='current_stage',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
