# Generated by Django 4.2.3 on 2023-08-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0005_alter_jobapplication_current_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[(0, 'Ожидает одобрения'), (1, 'Одобрено'), (2, 'Отклонено')], default='pending', max_length=20),
        ),
    ]
