# Generated by Django 4.2.3 on 2023-08-21 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0006_alter_jobapplication_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='status',
            new_name='approval_status',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='current_stage',
            new_name='current_admin_stage',
        ),
    ]
