# Generated by Django 4.2.3 on 2023-08-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0010_alter_jobapplication_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
