# Generated by Django 4.2.2 on 2023-08-20 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0002_alter_adminprofile_options_alter_adminprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='priority',
        ),
    ]
