# Generated by Django 4.2.3 on 2023-08-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0003_remove_adminprofile_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, 'Админ'), (2, 'Администратор 1'), (3, 'Администратор 2'), (4, 'Администратор 3')]),
        ),
    ]
