# Generated by Django 4.2.3 on 2023-08-24 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0011_job_slug'),
        ('dashboardapp', '0005_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='forms_app.job'),
        ),
    ]
